package com.example.ui.util

object AppStrings {
  fun get(key: String, language: String = "en"): String {
    val isBangla = language == "bn"
    return when (key) {
      "app_name" -> if (isBangla) "ইভেন্ট ম্যানেজার" else "Event Manager"
      "tagline" -> if (isBangla) "পারিবারিক ও ব্যক্তিগত উৎসব পরিকল্পনার বিশ্বস্ত সঙ্গী" else "Plan weddings, feasts, and family gatherings seamlessly"
      "welcome_back" -> if (isBangla) "স্বাগতম," else "Welcome back,"
      "next_event" -> if (isBangla) "আসন্ন ইভেন্ট" else "Next event"
      "days_left" -> if (isBangla) "দিন বাকি" else "days left"
      "days" -> if (isBangla) "দিন" else "days"
      "today" -> if (isBangla) "আজ" else "today"
      "quick_actions" -> if (isBangla) "দ্রুত কাজ" else "Quick actions"
      "new_event" -> if (isBangla) "নতুন ইভেন্ট" else "New event"
      "add_contact" -> if (isBangla) "যোগাযোগ যোগ" else "Add contact"
      "add_expense" -> if (isBangla) "খরচ যোগ" else "Add expense"
      "expense_overview" -> if (isBangla) "ব্যয় ওভারভিউ" else "Expense Overview"
      "budget_overview" -> if (isBangla) "বাজেট ওভারভিউ" else "Budget Overview"
      "select_event" -> if (isBangla) "ইভেন্ট নির্বাচন করুন" else "Select Event"
      "passed" -> if (isBangla) "হয়েছে" else "Passed"
      "total_spent" -> if (isBangla) "মোট ব্যয়" else "Total Spent"
      "total_budget" -> if (isBangla) "মোট বাজেট" else "Total Budget"
      "your_events" -> if (isBangla) "আপনার ইভেন্টসমূহ" else "Your events"
      "see_all" -> if (isBangla) "সব দেখুন" else "See all"
      "add_guest" -> if (isBangla) "অতিথি যোগ" else "Add guest"
      "checklist" -> if (isBangla) "চেকলিস্ট" else "Checklist"
      "guests" -> if (isBangla) "অতিথিবৃন্দ" else "Guests"
      "vendors" -> if (isBangla) "ভেন্ডর" else "Vendors"
      "budget" -> if (isBangla) "বাজেট" else "Budget"
      "cost" -> if (isBangla) "ব্যয়" else "Cost"
      "planned" -> if (isBangla) "পরিকল্পিত" else "Planned"
      "spent" -> if (isBangla) "খরচ হয়েছে" else "Spent"
      "remaining" -> if (isBangla) "অবশিষ্ট" else "Remaining"
      "spending_by_category" -> if (isBangla) "ক্যাটাগরি ভিত্তিক খরচ" else "Spending by category"
      "recent_expenses" -> if (isBangla) "সাম্প্রতিক খরচসমূহ" else "Recent expenses"
      "contacts" -> if (isBangla) "যোগাযোগের তালিকা" else "Contacts"
      "settings" -> if (isBangla) "সেটিংস" else "Settings"
      "sign_in" -> if (isBangla) "সাইন ইন" else "Sign in"
      "sign_up" -> if (isBangla) "সাইন আপ" else "Sign up"
      "create_account" -> if (isBangla) "অ্যাকাউন্ট তৈরি করুন" else "Create your account"
      "logout" -> if (isBangla) "লগ আউট" else "Log out"
      "preferences" -> if (isBangla) "পছন্দসমূহ" else "Preferences"
      "language" -> if (isBangla) "অ্যাপের ভাষা" else "App language"
      "dark_mode" -> if (isBangla) "ডার্ক মোড" else "Dark mode"
      "currency" -> if (isBangla) "মুদ্রা" else "Currency"
      "accent_color" -> if (isBangla) "অ্যাকসেন্ট রং" else "Accent color"
      "data_and_backup" -> if (isBangla) "ডাটা ও ব্যাকআপ" else "Data & Backup"
      "backup_cloud" -> if (isBangla) "ক্লাউডে ব্যাকআপ সংরক্ষণ" else "Backup to cloud"
      "notifications" -> if (isBangla) "বিজ্ঞপ্তি / নোটিফিকেশন" else "Notifications"
      "filter_all" -> if (isBangla) "সব" else "All"
      "filter_family" -> if (isBangla) "পরিবার" else "Family"
      "filter_friend" -> if (isBangla) "বন্ধু" else "Friend"
      "filter_vendor" -> if (isBangla) "ভেন্ডর" else "Vendor"
      "filter_other" -> if (isBangla) "অন্যান্য" else "Other"
      "status_confirmed" -> if (isBangla) "নিশ্চিত" else "Confirmed"
      "status_called" -> if (isBangla) "কল করা হয়েছে" else "Called"
      "status_not_called" -> if (isBangla) "কল বাকি" else "Not Called"
      "status_declined" -> if (isBangla) "অপারগ" else "Declined"
      "add_task" -> if (isBangla) "+ টাস্ক যোগ করুন" else "+ Add task"
      "add_new" -> if (isBangla) "নতুন যোগ করুন" else "Add new"
      "import_phone" -> if (isBangla) "কন্টাক্ট ইমপোর্ট" else "Import Contacts"
      "add_new_contact" -> if (isBangla) "নতুন কন্টাক্ট" else "Add Contact"
      "create_event_button" -> if (isBangla) "ইভেন্ট তৈরি করুন" else "Create event"
      "event_title" -> if (isBangla) "ইভেন্টের নাম" else "Event title"
      "category" -> if (isBangla) "ক্যাটাগরি" else "Category"
      "date" -> if (isBangla) "তারিখ" else "Date"
      "time" -> if (isBangla) "সময়" else "Time"
      "location" -> if (isBangla) "স্থান / ভেন্যু" else "Location"
      "planned_budget" -> if (isBangla) "পরিকল্পিত বাজেট" else "Planned budget"
      "due" -> if (isBangla) "বাকি" else "Due"
      "paid" -> if (isBangla) "পরিশোধিত" else "Paid"
      "payment_schedule" -> if (isBangla) "পেমেন্ট শিডিউল" else "Payment Schedule"
      "payments_due" -> if (isBangla) "পেমেন্ট বাকি" else "Payments Due"
      "overdue" -> if (isBangla) "মেয়াদোত্তীর্ণ" else "Overdue"
      "due_this_week" -> if (isBangla) "এই সপ্তাহে বাকি" else "Due This Week"
      "upcoming" -> if (isBangla) "আসন্ন" else "Upcoming"
      "due_date" -> if (isBangla) "পরিশোধের শেষ তারিখ" else "Payment Due Date"
      "advance_paid" -> if (isBangla) "অগ্রিম পরিশোধ" else "Advance Paid"
      "remaining_due" -> if (isBangla) "অবশিষ্ট বাকি" else "Remaining Due"
      "schedule" -> if (isBangla) "সময়সূচী" else "Schedule"
      "add_function" -> if (isBangla) "+ ফাংশন যোগ" else "+ Add Function"
      "multi_day_schedule" -> if (isBangla) "মাল্টি-ডে সময়সূচী" else "Multi-Day Schedule"
      "no_payment_schedule" -> if (isBangla) "কোনো নির্ধারিত পেমেন্ট শিডিউল নেই" else "No payment schedule set"
      "all_payments_clear" -> if (isBangla) "সব ভেন্ডর পেমেন্ট পরিশোধিত!" else "All vendor payments are clear!"
      else -> key
    }
  }
}
